Test refactored scripts in new notebook
Currently not working, using sklearn pipeline introduced some oddities and possible lack of flexibility

ValueError: too many values to unpack (expected 2) was the problem on fitting and transforming the overall text corpus through CV and TFIDF